### ISSUE TITLE
Is this using XNLRankBar

### ISSUE THREAD

**Issue by toddhow** [Mobius1/esx_xp#1]
I am wondering cause it looks alot like it

**Comment by Mobius1** [comment]
No, I thought about using it, but this uses one I created using HTML5 / JS / CSS3 based on the GTA:O native one.

**Comment by toddhow** [comment]
Also It would be cool if you recreated the scoreboard

**Comment by Mobius1** [comment]
Sounds good. I'll add the scoreboard as a config option in a future release.
