### ISSUE TITLE
Leaderboard pagination problem.

### ISSUE THREAD

**Issue by cuBeUrg** [Mobius1/esx_xp#11]
![image](https://user-images.githubusercontent.com/42491195/96037311-56c6e980-0e6e-11eb-9540-35dd620cc8d7.png)

**Comment by cuBeUrg** [comment]
Ok, so I found out exactly how this problem happens. So, let's say we add 5 pages of players, when we are on the 5th page, and remove the players, the error will show up.

**Comment by Mobius1** [comment]
This was fixed in the latest update: https://streamable.com/38yoej

**Comment by cuBeUrg** [comment]
> This was fixed in the latest update: https://streamable.com/38yoej

Great. It works nicely. Thanks for the update.
