### ISSUE TITLE
learderboard.updateRank is not a function

### ISSUE THREAD

**Issue by ImStayFrosty** [Mobius1/esx_xp#5]
I get this error when I disable the leaderboard in the config. Another error I get is Failed to fetch (@esx_xp/ui/ui.html:0)
![image](https://user-images.githubusercontent.com/10207200/95278178-9ada3e80-081d-11eb-938a-86f207b6c761.png)
![image](https://user-images.githubusercontent.com/10207200/95278190-a0378900-081d-11eb-9c15-b9d8cea6f67e.png)

**Comment by Mobius1** [comment]
This is fixed in [v1.0.6](https://github.com/Mobius1/esx_xp/releases/tag/1.0.6).
