### ISSUE TITLE
Leaderboard - Different Problems

### ISSUE THREAD

**Issue by cuBeUrg** [Mobius1/esx_xp#6]
Hi! First of all, your script in really nice. However, I found 3 problems, while testing it, both problems are related to the scoreboard.

1) The first problem is that, when there are more than 30 players, the scoreboard looks kinda bad, here is a example:

![image](https://user-images.githubusercontent.com/42491195/95422679-67e09980-0948-11eb-928d-91d21a4cbf07.png)

2) The second problem is that, when I am alone on the server, I don't show up on the leaderboard. Here is the proof:

![image](https://user-images.githubusercontent.com/42491195/95422798-a0807300-0948-11eb-935a-7babf7fbc8d5.png)

3) The third problem is that after typing the commands (ESXP_RemoveFakePlayers / ESXP_AddFakePlayer), it gives me errors in the F8. 

![image](https://user-images.githubusercontent.com/42491195/95422881-c73ea980-0948-11eb-915c-cddd2b1e3bd4.png)

**Comment by Mobius1** [comment]
Thanks for the report. Number 1 and 3 are fixed in the master branch, but I'm still looking into number 2.

**Comment by cuBeUrg** [comment]
I found a idea of how you can fix the first problem. 

https://i.imgur.com/6oFDHtD.gif

**Comment by Mobius1** [comment]
Pagination is a good idea!

**Comment by Mobius1** [comment]
Pagination added to [v1.1.0](https://github.com/Mobius1/esx_xp/releases/tag/1.1.0).

Still looking into the missing player bug.

**Comment by cuBeUrg** [comment]
Also, when adding players, there are some console error:

![image](https://user-images.githubusercontent.com/42491195/95470255-3fc55a80-0989-11eb-844c-26ee2b848d04.png)

**Comment by Mobius1** [comment]
Should be fixed in [v1.1.1](https://github.com/Mobius1/esx_xp/releases/tag/1.1.1).

**Comment by cuBeUrg** [comment]
Found some more problems. If I'm alone on the server, and press Z, after the menu shows up, it gives me some errors in the console. 

![image](https://user-images.githubusercontent.com/42491195/95554523-fc1a3180-0a18-11eb-9772-314c3fd3c222.png)

Also, this is how the menu looks, after pressing Z:

![image](https://user-images.githubusercontent.com/42491195/95554602-1e13b400-0a19-11eb-9214-c208502616ee.png)

Also, the leaderboard never fades out for me. Even if in the config it is set to 5 sec, it dosen't fade out.

**Comment by cuBeUrg** [comment]
Ok, tested the new version and everything works nicely. Now the only problem left is the one with when there is only one player on the server. Hope it gets fixed soon! 🥇

**Comment by cuBeUrg** [comment]
Ok, so regarding the problem with the player not showing up on the leaderboard. Maybe you can try to make that the source (player), is always the first one on the list?

**Comment by cuBeUrg** [comment]
Hi! Managed to get some friends on the server, but still, there are no players on the Z. 

Also, after adding some fake players, and then removing them, the page dosen't go back to one.
