### ISSUE TITLE
Error in leaderboard

### ISSUE THREAD

**Issue by chopo156** [Mobius1/esx_xp#7]
https://prnt.sc/uw4zsn

i test the new update and when i try to open the leaderboard this appeard

**Comment by Mobius1** [comment]
Check you have the `ui/js/class.paginator.js` file.

**Comment by chopo156** [comment]
https://prnt.sc/uweapj yes i have

**Comment by chopo156** [comment]
Dont worry, i just delete de cache again and now works flawless!
