### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by cuBeUrg** [Mobius1/esx_xp#9]
![image](https://user-images.githubusercontent.com/42491195/95839186-63065600-0d4b-11eb-87a5-29dfd93bfd65.png)

This errors show up when I try to open the menu.

**Comment by cuBeUrg** [comment]
Find this: ` v.license = string.gsub(v.license, "license:", "")`
And replace with this:  `v.license = string.gsub(license, "license:", "")`

**Comment by cuBeUrg** [comment]
Everything works nicely! Well done @Mobius1 . Thanks for taking your time to create this script.

**Comment by Mobius1** [comment]
That seems to be a problem with the `fetch` implementation in the version of Chrome that the NUI uses. The call is successful, but it still throws an error.

**Comment by cuBeUrg** [comment]
> That seems to be a problem with the `fetch` implementation in the version of Chrome that the NUI uses. The call is successful, but it still throws an error.

Is there a way to remove that error?

**Comment by Mobius1** [comment]
The fetch error should be fixed in the `master` branch
